services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ev_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nayan123@
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1-python3.11
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Nayan123%40@postgres/ev_pipeline
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _PIP_ADDITIONAL_REQUIREMENTS: "joblib prophet scikit-learn pandas psycopg2-binary python-dotenv requests"
      NREL_API_KEY: lSFcyI4LIRzI092padCZzmi7Vsi0RaTQAbKen85W
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ev_pipeline
      DB_USER: postgres
      DB_PASSWORD: "Nayan123@"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
      - ./sql:/opt/airflow/sql
    command: standalone

volumes:
  pgdata:
